### ISSUE TITLE
How get all diamonds record count

### ISSUE THREAD

**Issue by abidgemsny** [Nivoda/nivoda-api#2]
Hi

As pre below query I have get the total count of diamonds base on query parameter like labgrown: false.

if labgrown: false that means it will provide Natural Diamond count 
if labgrown: true that means it will provide Lab Diamond count 
But I need all Diamond product count how can I please help

```
{
    diamonds_by_query_count(
        query: {
            labgrown: false
        }
     )
}
```

**Comment by andrewoons** [comment]
Hi,

you would have to fetch both separately as they are different products.
