### ISSUE TITLE
diamond_by_id query not found 

### ISSUE THREAD

**Issue by abidgemsny** [Nivoda/nivoda-api#3]
diamond_by_id , certificate_by_cert_number and diamond_by_cert_number not working or not call.

Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [message] => GraphQLError: Cannot query field "diamond_by_id" on type "Query". Did you mean "diamonds_by_query"?
    at Object.Field (. null
                    [locations] => Array
                        (
                            [0] => Array
                                (
                                    [line] => 2
                                    [column] => 13
                                )

                        )

                    [already_sent_to_sentry] => 1
                )

        )

)

**Comment by robwent** [comment]
According to the docs and the error message, the correct query is `diamonds_by_query`.

For a single diamond, there's `get_diamond_by_id`.
