### ISSUE TITLE
has_image query parameter doesn't seem to work

### ISSUE THREAD

**Issue by robwent** [Nivoda/nivoda-api#5]
I'm trying to only get diamonds that have an image

```graphql
query {
	diamonds_by_query(
		query: {
			availability:AVAILABLE
			labgrown: false
			shapes: ["ROUND"]
			sizes: [{ from: 1, to: 1.5 }]
			has_image: true
		}
		offset: 0
		limit: 50
		order: { type: price, direction: ASC }
	) {
		items {
			id
			diamond {
				id
				video
				image
				availability
				certificate {
					id
					shape
					certNumber
					cut
				}
			}
			price
			discount
		}
		total_count
	}
}
```

But the result that come through all seem to have images set to null:
![images](https://user-images.githubusercontent.com/411678/213609496-e690f419-3675-4b62-a203-e179c3e1b5d6.png)

What am I doing wrong?

**Comment by templatetuners** [comment]
same for me

**Comment by robwent** [comment]
@templatetuners From what I can remember, this issue only happened with the testing API and moving to the production one got it working.

This was the response from devs, but it doesn't seem to apply to my original screenshot:

> Regarding the image query discrepancy, if both image and video filter are applied, the query will return results that have either/or, not both, ergo the missing image fields. To ensure the filter primarily checks images, try removing the "has_v360" filter.

**Comment by templatetuners** [comment]
filter is broken if you apply both `has_image: true` and `has_v360: true`

**Comment by templatetuners** [comment]
I am still getting products without images when I have both has_image and 360 > true
