### ISSUE TITLE
HTML elements for the provided video links

### ISSUE THREAD

**Issue by resistorsoftware** [Nivoda/nivoda-api#7]
The API returns a video URL for a diamond. 

`https://loupe360.com/diamond/uniglobvCS65244/video/500/500`

So I am getting a URI to something 500x500 pixels big. What HTML is appropriate to show off this link?  It is not an *img* and it is not a *video* so what HTML tag can we use to just show off the contents of this link. I see it renders on a canvas element if you visit that link, but obviously I don't want to visit this link. Am I expected to scrape the HTML and render that chunk of code? 

loupe360.com is password protected and thus offers up no insight or help in this matter. Gatekeeping? I am curious as to why this is a thing. With an API account at Nivoda, and being fed URLs, what is the best way to just render these 360 loupe creations without too much trouble.

If we have nothing but the old <iframe> element, then I guess that solves that, but I was hoping it was not throwback days code...

**Comment by Hermitauge** [comment]
same question!! There is no documentation on how to properly pull the videos, my client even already has the v360 machine. Can you guys please release a demo template of properly pulling video and displaying it without getting a million console logs

**Comment by andrewoons** [comment]
@Hermitauge @resistorsoftware 
We currently only support <iframe> for the videos
