### ISSUE TITLE
price query is not working in Nivoda api 

### ISSUE THREAD

**Issue by Furquanwork** [Nivoda/nivoda-api#8]
query {
      diamonds_by_query(
        query: {
          labgrown: false,
          shapes: ["ROUND"],
          sizes: [{ from: 1, to: 1.5}],
          discount: { from: 0 , to: 7000},
          has_v360: true,
          has_image: true,
          color: [D,E],
           cut: GD,
          clarity: VS1,
          price: [{from:1000, to: 15000}]
        },
         
        offset: 0,
        limit: 3, 
        order: { type: price, direction: ASC }
      ) {
        items {
          id
          diamond {
            id
            video
            image
            availability
            supplierStockId
            brown
            green
            milky
            eyeClean
            mine_of_origin
            certificate {
              id
              lab
              shape
              certNumber
              cut
              carats
              clarity
              polish
              symmetry
              color
              width
              length
              depth
              girdle
              floInt
              floCol
              depthPercentage
              table
            }
          }
          price
          discount
        }
        total_count
      }
    }
    
    can someone help to find issue, it is not filtering based on price

**Comment by Hermitauge** [comment]
im curious as to why Nivoda doesn't respond to issues referenced here. Surely, 30 minute a month to checkin here isn't much to ask. Don't know if I should keep recommending Nivoda

**Comment by andrewoons** [comment]
@Furquanwork I believe your issues was resolved over email but please do let us know if you are still encountering any issues.
